Link to FOSSA report in GitHub job summary

diff --git a/.github/workflows/dependency-review.yml b/.github/workflows/dependency-review.yml
--- a/.github/workflows/dependency-review.yml
+++ b/.github/workflows/dependency-review.yml
@@ -26,5 +26,14 @@ jobs:
       - name: FOSSA dependency license check
         run: |
           curl --no-progress-meter -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/v${FOSSA_CLI_VERSION}/install-latest.sh | bash
-          fossa analyze --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }} --revision ${{ github.sha }}
+
+          echo '## FOSSA dependency license check' >> $GITHUB_STEP_SUMMARY
+          echo '' >> $GITHUB_STEP_SUMMARY
+
+          fossa analyze --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }} --revision ${{ github.sha }} | tee fossa_analyze.log
           fossa test --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }} --revision ${{ github.sha }}
+
+          TEST_FAILED=$?
+          FOSSA_REPORT_LINK="$(cat fossa_analyze.log grep -A 1 '[ INFO] View FOSSA Report:' | tail -n 1 | sed -e 's/^\[ INFO]\s*//')""
+          echo "[FOSSA detected $([ $TEST_FAILED -ne 0 ] && echo -n '' || echo 'no ')issues](${FOSSA_REPORT_LINK})" >> $GITHUB_STEP_SUMMARY
+          exit $TEST_FAILED
